import '@/styles/globals.css'
import type { Metadata } from 'next'
import ScopedCssBaseline from '@mui/material/ScopedCssBaseline';
import LayOut from '@/components/MainLayout';
import { ReduxProvider } from '@/redux/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} >
        <ReduxProvider>
          <ScopedCssBaseline>
          <LayOut>
            {children}
          </LayOut>
          </ScopedCssBaseline>
        </ReduxProvider>
      </body>
    </html>
  )
}